Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Example.Models;
using Example.Data;

namespace Example.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public ChatController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            var users = (from user in _context.Users  
                        select new  
                        {  
                            UserId = user.Id,                                        
                            FirstName = user.FirstName,  
                            LastName = user.LastName,
                            Picture = user.Picture,
                            Email = user.Email,
                            City = user.City,
                            State = user.State
                        }).ToList()
                        .Select(u => new ApplicationUser()  
                        {  
                            Id = u.UserId,  
                            FirstName = u.FirstName, 
                            LastName = u.LastName, 
                            Picture = u.Picture,
                            Email = u.Email,
                            City = u.City,
                            State = u.State
                        });  
                        
            users = users.OrderBy(u => u.Email);
            return View(users.ToList());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult Conversation(string id)
        {    
            var userId =  User.FindFirstValue(ClaimTypes.NameIdentifier);

            var messages = (from message in _context.Messages
                            select new   
                            { 
                                MessageId = message.MessageId,
                                SenderId = message.SenderId,
                                ReceiverId = message.ReceiverId,
                                Message = message.Message,
                                CreateDate = message.CreateDate
                            }).Select(m => new MessageModel()  
                            {  
                                MessageId = m.MessageId,
                                SenderId = m.SenderId,
                                ReceiverId = m.ReceiverId,
                                Message = m.Message,
                                CreateDate = m.CreateDate
                            })
                            .Where(c => (c.ReceiverId == id && c.SenderId == userId.ToString()) || 
                                            (c.ReceiverId == userId.ToString() && c.SenderId == id))
                            .OrderBy(c => c.CreateDate);

            return View(messages.ToList());
        }

        public IActionResult SendMessage(string id, string content, MessageModel message)
        {
            var userId =  User.FindFirstValue(ClaimTypes.NameIdentifier);

            message.ReceiverId = id;
            message.Message = content; // Get a warning here. Should probably change Message to Content as well.
            message.SenderId = userId;
            message.Status = 0; // Not really need. Kind of a false start.
            message.CreateDate = DateTime.Now;


            _context.Messages.Add(message);
            _context.SaveChangesAsync();

            return RedirectToAction("Conversation", new {id = id});
        }
    }
}

Views/Chat/Conversation.cshtml
@model IEnumerable<Example.Models.MessageModel>
@using Example.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Conversation";
    var user = await UserManager.GetUserAsync(User);
    var receiverId = "";
    var senderId = "";
}

<h4>@ViewData["Title"]</h4>
<form method="post" enctype="multipart/form-data">
    <div class="row form-group">
        <div class="col-md-6" style="margin: 0 auto;">
            <ul id="contacts" class="container list-group" style="min-height: 200px; background-color: #f5f5f5;list-style-type: none;border-radius: 5px; padding: 0 15px;">                        
                @foreach (var message in Model) 
                {
                    @if(@message.SenderId == @user.Id) 
                    {
                        <li style="display:inline-block;clear: both; margin: 2px;float:right;"><span class="float-right bg-primary text-white" style="width: auto;border-radius: 7px;padding: 1% 2%;">@message.Message</span></li>
                    }
                    else 
                    {
                        <li style="display:inline-block;clear: both;margin: 2px;"><span class="float-left bg-success text-white" style="width: auto;border-radius: 7px;padding: 1% 2%;">@message.Message</span></li>
                    }
                    receiverId = @message.ReceiverId;
                    senderId = @message.SenderId;
                }
            </ul>
        </div>
    </div>

</form>
    @using(Html.BeginForm("SendMessage","Chat"))
    {
    <div class="row form-group">
        @if (user.Id == @receiverId)
        {
            <input type="hidden" name="id" value="@senderId" />
        }
        else 
        {
            <input type="hidden" name="id" value="@receiverId" />
        }
        <div class="col-md-6" style="margin: 0 auto;">
            <input name="content" class="form-group input-group" style="min-height:30px;height:auto;background-color: #f5f5f5;border-radius: 5px;border: transparent;" />
            <button class="input-group-button btn btn-primary" style="width:100%;">Send</button>
        </div>
    </div>
    }

Views/Chat/Index.cshtml
@model IEnumerable<Example.Models.ApplicationUser>
@using Example.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Chat";
    var user = await UserManager.GetUserAsync(User);
}

<h4>@ViewData["Title"]</h4>
<form method="post" enctype="multipart/form-data">
    <div class="container">
        <div class="panel-body">
            <ul id="contacts" class="list-group">                        
                @foreach (var users in Model) 
                {
                <a asp-action="Conversation" asp-route-id="@users.Id">
                    <li>
                        <span> <img src="@users.Picture" style="border-radius: 50%;width: 30px;height: 30px;"> @users.Email</span>
                        <div class="status-bar"></div>
                    </li>
                </a>
                }
            </ul>
        </div>
    </div>
</form>